# Generated by Django 5.2.1 on 2026-04-06 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0002_savedjob'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedCV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidate_name', models.CharField(max_length=255)),
                ('candidate_email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=50)),
                ('cv_file', models.FileField(upload_to='uploaded_cvs/')),
                ('cv_text', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True, help_text='Internal admin notes about this CV')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_cvs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Uploaded CV',
                'verbose_name_plural': 'Uploaded CVs',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='CVScreeningResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField(default=0)),
                ('score_breakdown', models.JSONField(default=dict)),
                ('strengths', models.JSONField(default=list)),
                ('weaknesses', models.JSONField(default=list)),
                ('recommendation', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('screened_at', models.DateTimeField(auto_now_add=True)),
                ('gemini_model_used', models.CharField(default='gemini-1.5-flash', max_length=50)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_screening_results', to='jobs.job')),
                ('cv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_results', to='cv_screening.uploadedcv')),
            ],
            options={
                'verbose_name': 'CV Screening Result',
                'verbose_name_plural': 'CV Screening Results',
                'ordering': ['-overall_score'],
                'unique_together': {('cv', 'job')},
            },
        ),
    ]
