# Generated by Django 5.2.1 on 2026-04-06 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedcv',
            name='category',
            field=models.CharField(choices=[('engineering', 'Engineering & Tech'), ('design', 'Design & Creative'), ('product', 'Product & Management'), ('marketing', 'Marketing & Growth'), ('sales', 'Sales & Business Dev'), ('finance', 'Finance & Accounting'), ('hr', 'HR & Recruitment'), ('operations', 'Operations & Logistics'), ('data', 'Data & Analytics'), ('customer_support', 'Customer Support'), ('legal', 'Legal & Compliance'), ('other', 'Other')], default='other', help_text='Role category — used for basic filtering and grouping', max_length=50),
        ),
        migrations.AlterField(
            model_name='cvscreeningresult',
            name='gemini_model_used',
            field=models.CharField(default='gemini-2.5-flash', max_length=50),
        ),
        migrations.AlterField(
            model_name='uploadedcv',
            name='notes',
            field=models.TextField(blank=True, help_text='Internal notes about this CV'),
        ),
    ]
