# Generated by Django 5.2.1 on 2026-04-08 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv_screening', '0002_uploadedcv_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvscreeningresult',
            name='error_message',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='cvscreeningresult',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='completed', max_length=20),
        ),
    ]
